PluginSettings:
  Warp:
    toml: true
    yaml: false
    json: false
    mysql: false
Teleport:
  cooldown: 60
  countdown: 3
WildTP:
  Radius:
    maxX: 10000
    minX: -10000
    maxZ: 10000
    minZ: -10000
  SafeBlocks:
    - GRASS
    - STONE
    - SNOW
    - SNOW_LAYER
