name: OhneeEssentials
version: 1.0
main: com.ohneemc.OhneeEssentials.OhneeEssentials
api-version: 1.14
commands:
  wild:
    description: Randomly teleports you in the world.
    usage: /Wild
    aliases: [rtp, wilderness]
    permission: ohnee.basic
    permission-message: You do not have access to this command /Wild.
  ohnee:
    description: Access to admiin commands.
    usage: Missing arguments - /ohnee reload or /ohnee version
    permission: ohnee.admin
    permission-message: You do not have access to this command /Ohnee.
  tp:
    description: Teleport you to a player.
    usage: Missing arguments - /ohnee reload or /ohnee version
    permission: ohnee.tp
    permission-message: You do not have access to this command /tp.
  tphere:
    description: Teleport a player to you.
    usage: Missing arguments - /ohnee reload or /ohnee version
    permission: ohnee.tphere
    permission-message: You do not have access to this command /tphere.
  weather:
    description: Sets the current worlds weather!
    usage: Missing arguments - /weather clear|thunder|rain <duration in seconds>
    permission: ohnee.weather
    permission-message: You do not have access to this command /weather.
  time:
    description: Sets the current worlds time!
    usage: Missing arguments - /time day|night
    permission: ohnee.time
    permission-message: You do not have access to this command /time.
permissions:
  ohnee.*:
    default: false
    description: access to every command in OhneeEssentials.
    children:
      ohnee.basic: true
      ohnee.admin: true
      ohnee.tp: true
      ohnee.tphere: true
      ohnee.weather: true
      ohnee.time: true