name: OhneeEssentials
version: 1.0
main: com.ohneemc.OhneeEssentials.OhneeEssentials
api-version: 1.14
commands:
  wild:
    description: Randomly teleports you to a location in your current world.
    usage: /Wild
    aliases: [rtp, wilderness]
    permission: ohnee.basic
    permission-message: You do not have access to this command(/Wild).
  ohnee:
    description: Access to admiin commands
    usage: /Ohnee
    permission: ohnee.admin
    permission-message: You do not have access to this command(/Ohnee).