name: OhneeEssentials
version: 1.0
main: com.ohneemc.OhneeEssentials.OhneeEssentials
api-version: 1.14
commands:
  wild:
    description: Randomly teleports you in the world.
    usage: /Wild
    aliases: [rtp, wilderness]
    permission: ohnee.basic
    permission-message: You do not have access to this command /Wild.
  ohnee:
    description: Access to admiin commands
    usage: Missing arguments - /ohnee reload or /ohnee version
    permission: ohnee.admin
    permission-message: You do not have access to this command /Ohnee.
permissions:
  ohnee.*:
    default: false
    description: access to every command in OhneeEssentials.
    children:
      ohnee.basic: true
      ohnee.admin: true